-- Plantilla del curso “Docerola Tumbada” + la mentoría grupal (oculta).
-- GENERADO por scripts/curso-docerola/generar-seed.mjs desde temario.mjs — no editar a mano.
-- Requiere supabase-cursos-v2.sql. Idempotente: si el curso ya existe, no hace nada
-- (así nunca pisa lo que ya escribiste en el panel).
-- Todas las lecciones nacen SIN publicar: el alumno no ve nada hasta que la grabes y la publiques.

do $$
declare
  v_curso uuid;
  v_mentoria uuid;
  v_mod uuid;
begin
  if exists (select 1 from public.cursos where slug = 'docerola-tumbada') then
    raise notice 'El curso docerola-tumbada ya existe: no se toca nada.';
    return;
  end if;

  -- Mentoría (tipo 'mentoria'): nadie la ve hasta que se le dé acceso a alguien.
  insert into public.cursos (slug, titulo, descripcion, activo, tipo)
    values ('mentoria-docerola', 'Mentoría grupal semanal', 'Sesiones en vivo cada semana: corrección de vicios, rolas que no te salen y revisión de tus arreglos.', true, 'mentoria')
    returning id into v_mentoria;
  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_mentoria, 'Sesiones en vivo', 0, 'bonus', 'La próxima sesión, con su enlace. Después se le pega la grabación.') returning id into v_mod;
  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_mentoria, 'Grabaciones', 1, 'bonus', 'Todas las sesiones pasadas.') returning id into v_mod;

  -- El curso. Nace oculto (activo = false) hasta que decidas lanzarlo; la mentoría
  -- queda ligada pero apagada (estado 'oculta').
  insert into public.cursos (slug, titulo, descripcion, activo, tipo, revisiones_incluidas, config)
    values ('docerola-tumbada', 'Docerola Tumbada', 'Del primer rasgueo al requinto propio: aprende docerola para corridos tumbados con criterio, sin depender de tutoriales.', false, 'curso', 1,
      jsonb_build_object('meta_semanal_min', 150, 'landing', '{"promesa":"[RELLENAR: qué va a poder tocar el alumno al terminar, en una o dos frases (ej. rasgueo tumbado, su propio requinto y criterio para sacar cualquier rola)]","para_quien":"[RELLENAR: un punto por renglón: para quién SÍ es el curso]","no_para_quien":"[RELLENAR: un punto por renglón: para quién NO es (filtra a quien busca atajos)]","garantia":"[RELLENAR: tu política de reembolso o garantía — revísala con el abogado antes de publicar]","faqs":"[RELLENAR: preguntas frecuentes como P: … / R: …, separadas por un renglón en blanco (¿necesito saber leer partitura?, ¿sirve para requinto?, ¿cuánto tiempo tengo acceso?, ¿qué docerola necesito?)]"}'::jsonb,
        'mentoria', jsonb_build_object('estado', 'oculta', 'curso_id', v_mentoria::text, 'precio_mes', null)))
    returning id into v_curso;

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M0 · Arranque', 0, 'principal', 'Tu primera victoria en 20 minutos y cómo sacarle todo al curso.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '0.1 Bienvenida: lo que vas a poder tocar', 'video', 'nucleo', false, true, 'ninguno',
     '{"objetivo":"[RELLENAR: que el alumno vea el resultado final del curso y sepa por qué este método es distinto]","gancho":"[RELLENAR: toca 30 s del requinto más impresionante que el alumno va a poder tocar al final]","minimo":"[RELLENAR: quién eres, qué te dio la música y la promesa del curso en una frase]","practica":"[RELLENAR: recorrido rápido: rasgueo → requinto → arreglo propio (lo que van a construir)]","criterio":"[RELLENAR: por qué no vas a depender de tutoriales: vas a entender el porqué de lo que tocas]","reto":"[RELLENAR: que escriba en su bitácora qué rola quiere poder tocar al terminar]","puente":"[RELLENAR: en 20 minutos ya vas a estar rasgueando tu primer tumbado]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '0.2 Cómo usar este curso', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: que sepa usar el ciclo Mínimo → Práctica → Criterio, las rutas y el reproductor]","gancho":"[RELLENAR: muestra el reproductor en 0.5x y repitiendo un pedazo: “así vas a practicar”]","minimo":"[RELLENAR: las 3 rutas: principal (obligatoria), profunda y evaluaciones (optativas); los Datos Crack]","practica":"[RELLENAR: demo del reproductor: velocidad, repetir A-B, modo espejo, capítulos; la bitácora y la racha]","criterio":"[RELLENAR: cuánto practicar al día y por qué es mejor poco diario que mucho el domingo]","reto":"[RELLENAR: registrar su primera práctica en la bitácora]","puente":"[RELLENAR: menciona de pasada que existe la mentoría en vivo; “más adelante te cuento”]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '0.3 Diagnóstico: ¿de dónde partes?', 'quiz', 'evaluacion', true, false, 'ninguno',
     '{"instrucciones":"[RELLENAR: contesta honesto; no hay respuestas malas: esto sólo te dice por dónde empezar]","preguntas":[{"pregunta":"¿Ya tocas guitarra de 6 cuerdas?","opciones":["Sí, con soltura","Un poco","Nunca"],"correcta":0},{"pregunta":"¿Puedes cambiar entre G, C y D sin parar el rasgueo?","opciones":["Sí","Todavía no"],"correcta":0},{"pregunta":"¿Sabes leer tablatura?","opciones":["Sí","No"],"correcta":0},{"pregunta":"¿Sabes qué es el grado V de una tonalidad?","opciones":["Sí","No"],"correcta":0},{"pregunta":"¿Has sacado una rola a oído?","opciones":["Sí","No"],"correcta":0}],"diagnostico":[{"min":0,"texto":"[RELLENAR: recomendación para quien empieza de cero, p. ej.: sigue el curso en orden, sin saltarte M1 y M2]"},{"min":40,"texto":"[RELLENAR: recomendación intermedia, p. ej.: ve rápido por M1–M2 y pon toda tu atención en M3]"},{"min":80,"texto":"[RELLENAR: recomendación avanzada, p. ej.: M1–M3 como repaso, el curso de verdad empieza en M4]"}]}'::jsonb, 2, false, 'guion'),
    (v_mod, '0.4 Tu primer rasgueo tumbado con 2 acordes', 'video', 'nucleo', false, true, 'ninguno',
     '{"objetivo":"[RELLENAR: rasguear un patrón tumbado básico con 2 acordes a tu tempo meta en bpm]","gancho":"[RELLENAR: toca el patrón con los 2 acordes sobre una pista y que se escuche ya a corrido]","minimo":"[RELLENAR: los 2 acordes (cuáles y por qué esos) y el patrón en palabras: abajo/arriba/apagado]","practica":"[RELLENAR: patrón a 60 bpm → cambio de acorde cada 2 compases → sobre la pista de acompañamiento]","criterio":"[RELLENAR: por qué empezamos por el rasgueo y no por el requinto]","reto":"[RELLENAR: 4 vueltas seguidas sin parar sobre la pista]","puente":"[RELLENAR: ahora sí: conoce el instrumento que tienes en las manos]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '¿Por qué la docerola suena “a coro”?', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: la frase gancho, p. ej.: tu docerola es un coro de 2 guitarras en un solo instrumento]","explicacion":"[RELLENAR: cuerdas en octava + pares que nunca quedan 100% afinados = batimiento, un chorus natural]","aplicacion":"[RELLENAR: por eso afinar bien los pares cambia todo el sonido (lo vemos en 1.2)]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 4, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M1 · Conoce tu docerola (lo que nadie te dice)', 1, 'principal', 'Lo que se vive en el día a día: afinación, cuerdas, mantenimiento y el capo como arma.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '1.1 Anatomía que sí usas', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: que ubique órdenes, octavas y unísonos, escala, acción y alma en SU docerola]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: 6 órdenes, cuáles van en octava y cuáles al unísono; qué es la acción y el alma (truss rod)]","practica":"[RELLENAR: recorrido físico por el instrumento con cámara cerrada]","criterio":"[RELLENAR: qué partes se ajustan en casa y cuáles son de laudero]","reto":"[RELLENAR: medir la acción de su docerola en el traste 12 (y anotarla)]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '1.2 Afinar la 12 sin sufrir', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: afinar los 12 en pocos minutos (di cuántos), con los pares sin batimiento]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: orden de afinado, afinar primero las gruesas, luego sus octavas; medio tono abajo sí o no]","practica":"[RELLENAR: afinador + oído: cómo escuchar el batimiento entre pares y eliminarlo]","criterio":"[RELLENAR: cuándo conviene afinar medio tono abajo (tensión, voz del cantante) y qué cambia]","reto":"[RELLENAR: afinar desde cero y grabar un acorde al aire: que no “tiemble”]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '1.3 Cuerdas: calibres, cuándo cambiarlas y cómo encordar', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: calibres que recomiendas para corrido tumbado y por qué; señales de cuerdas muertas]","practica":"[RELLENAR: encordar una 12 paso a paso: orden, vueltas en la clavija, estirado]","criterio":"[RELLENAR: cada cuánto cambiar según cuánto tocas y si tocas en vivo]","reto":"[RELLENAR: calcular cuándo le toca su siguiente cambio y anotarlo]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '1.4 Mantenimiento de supervivencia', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: humedad, calor (el carro), limpieza, estuche, viajes]","practica":"[RELLENAR: rutina de limpieza de 5 minutos y cómo guardarla]","criterio":"[RELLENAR: señales de alarma que requieren laudero (puente levantado, mástil vencido)]","reto":"[RELLENAR: checklist de mantenimiento aplicada a su instrumento]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '1.5 El capotraste como arma (1): tono y timbre', 'video', 'herramienta', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: el capo cambia el tono sin cambiar las posiciones; también cambia el timbre]","practica":"[RELLENAR: mismo rasgueo sin capo, capo 2, capo 4: escucha la diferencia]","criterio":"[RELLENAR: cuándo usar capo por la voz del cantante y cuándo por el color]","reto":"[RELLENAR: tocar el patrón de 0.4 en 3 posiciones de capo distintas]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, 'La tensión que carga tu mástil', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: la tensión total de un juego de 12 cuerdas vs uno de 6 (usa la tabla del fabricante de tus cuerdas)]","explicacion":"[RELLENAR: por qué el alma y el puente trabajan el doble, y por qué muchos afinan medio tono abajo]","aplicacion":"[RELLENAR: no dejes tu docerola afinada meses sin tocar si notas que el puente se levanta]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'Cedro vs abeto: ¿de verdad se oye?', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: la madera de la tapa cambia el sonido más que la de los aros y el fondo]","explicacion":"[RELLENAR: tapa sólida vs laminada; cedro (cálido, abre rápido) vs abeto (brillante, más headroom)]","aplicacion":"[RELLENAR: qué buscar si vas a comprar tu siguiente docerola]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 6, false, 'guion'),
    (v_mod, 'Historia express de la docerola en el regional', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: cómo y cuándo entró la 12 cuerdas al regional mexicano]","explicacion":"[RELLENAR: de dónde viene, quién la popularizó en el corrido, cómo llegó al tumbado]","aplicacion":"[RELLENAR: por qué hoy es la base armónica del género]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 7, false, 'guion'),
    (v_mod, '1.6 Guía de compra y calidades', 'video', 'profunda', true, false, 'ninguno',
     '{"objetivo":"[RELLENAR: que sepa elegir una docerola por su presupuesto y revisar una usada]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: laminada vs sólida, gamas de precio, marcas que recomiendas y por qué]","practica":"[RELLENAR: checklist en vivo revisando una docerola: mástil, trastes, puente, electrónica]","criterio":"[RELLENAR: en qué vale la pena gastar y en qué no]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 8, false, 'guion'),
    (v_mod, 'Tu instrumento es tu socio', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: cuidar la herramienta es respeto por el oficio]","historia_personal":"[RELLENAR: una historia tuya con un instrumento (el primero, uno que se te echó a perder, uno que te salvó un toque)]","pregunta_al_alumno":"[RELLENAR: ¿qué le debes hoy a tu instrumento?]"}'::jsonb, 9, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M2 · Tus dos manos', 2, 'principal', 'Postura, púa, presión mínima y cómo cazar tus propios vicios.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '2.1 Postura y agarre', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: sentado, parado, con correa; hombros y muñecas sin tensión]","practica":"[RELLENAR: ajustar la postura con el celular grabando de frente y de lado]","criterio":"[RELLENAR: la postura que ves en videos de conciertos vs la que te deja tocar 3 horas]","reto":"[RELLENAR: foto o video de su postura comparado con el tuyo]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '2.2 Mano derecha: el motor del corrido', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: tipo y grosor de púa, ángulo, muñeca vs antebrazo, el apagado]","practica":"[RELLENAR: rasgueo sólo en cuerdas graves / sólo agudas / completo; apagado con la palma]","criterio":"[RELLENAR: cuánta cuerda atacar según la sección de la rola]","reto":"[RELLENAR: 1 minuto de rasgueo a 70 bpm sin que se escuche el choque de la púa]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '2.3 Mano izquierda: presión mínima en 12 cuerdas', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: pulgar, arco de dedos y la presión justa (la 12 castiga el exceso)]","practica":"[RELLENAR: ejercicio de presión mínima: aflojar hasta que zumbe y volver a apretar]","criterio":"[RELLENAR: cómo hacer cejillas en la 12 sin dolor]","reto":"[RELLENAR: acorde con cejilla que suene limpio 10 veces seguidas]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '2.4 Calentamiento de 5 minutos', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: por qué calentar evita lesiones y acelera el aprendizaje]","practica":"[RELLENAR: rutina de 5 minutos: estiramiento + cromático 1-2-3-4 + rasgueo lento]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: hacer la rutina 5 días seguidos (se ve en la racha)]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '2.5 Vicios comunes y autodiagnóstico', 'video', 'nucleo', false, false, 'revision',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: los 5 vicios que más ves en alumnos]","practica":"[RELLENAR: cómo grabarse con el celular y revisarse con la checklist]","criterio":"[RELLENAR: qué vicios se corrigen solos y cuáles se vuelven lesión]","reto":"[RELLENAR: grabarse 1 minuto y marcar la checklist]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]","cta_texto":"[RELLENAR: la cámara no miente, pero tampoco te corrige: ofrece la revisión/mentoría]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '¿Por qué duelen más los dedos en una 12?', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: presionas el doble de cuerdas con la misma yema]","explicacion":"[RELLENAR: más cuerdas = más fuerza para la misma nota; el callo es una adaptación]","aplicacion":"[RELLENAR: presión mínima + sesiones cortas = callo sin lesión]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'Disciplina vs motivación', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: la motivación te arranca, el hábito te sostiene]","historia_personal":"[RELLENAR: una época en la que practicaste sin ganas y qué te dejó]","pregunta_al_alumno":"[RELLENAR: ¿a qué hora de tu día va a vivir tu práctica?]"}'::jsonb, 6, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M3 · Ritmo y rasgueo tumbado', 3, 'principal', 'El groove del tumbado, los acordes del 80% y tu primera rola completa.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '3.1 Lo mínimo de ritmo', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: pulso, compás y subdivisión: el tumbado vive en la subdivisión]","practica":"[RELLENAR: contar en voz alta mientras rasgueas; palmadas sobre la pista]","criterio":"[RELLENAR: cómo se siente adelantado vs relajado (“tumbado”) el mismo patrón]","reto":"[RELLENAR: rasgueo con metrónomo en 2 y 4]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '3.2 Los acordes del 80%', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: mayores, menores y séptimas en las posiciones que se usan en el corrido]","practica":"[RELLENAR: digitación de cada acorde y cómo suena en la 12]","criterio":"[RELLENAR: cuáles son las tonalidades más comunes del género y por qué]","reto":"[RELLENAR: tocar la lista de acordes en ciclo a 60 bpm]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '3.3 Patrón base del tumbado + variantes', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: el patrón base escrito como ↓ ↓↑ x ↑… (x = apagado)]","practica":"[RELLENAR: patrón base 60 → 90 bpm; variante 1 y 2; dónde cae el apagado]","criterio":"[RELLENAR: qué variante va en la estrofa y cuál en el coro]","reto":"[RELLENAR: patrón base a tu tempo meta limpio durante 2 minutos]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '3.4 Cambios de acorde limpios', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: el dedo ancla y el cambio anticipado]","practica":"[RELLENAR: cambios en ciclos de 1 minuto: contar cuántos logras]","criterio":"[RELLENAR: por qué un cambio a tiempo vale más que un acorde perfecto tarde]","reto":"[RELLENAR: 60 cambios por minuto entre los 2 acordes más difíciles]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '3.5 Rola ancla 1 completa', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: tocar completa la rola ancla 1 con la pista de acompañamiento]","gancho":"[RELLENAR: toca la rola completa]","minimo":"[RELLENAR: la estructura de la rola: intro, estrofa, coro; los acordes]","practica":"[RELLENAR: sección por sección, después con la pista a 60%, 80% y 100%]","criterio":"[RELLENAR: qué hace que tu versión suene a disco y no a ensayo]","reto":"[RELLENAR: grabarse tocando la rola completa sobre la pista]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '3.6 Leer tablatura en 5 minutos', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: líneas = órdenes, números = trastes, cómo se escribe el ritmo en tab]","practica":"[RELLENAR: leer la intro de la rola ancla con la tablatura interactiva]","criterio":"[RELLENAR: cuándo basta la tab y cuándo conviene la partitura (Ruta Profunda)]","reto":"[RELLENAR: leer y tocar una frase de 2 compases que nunca ha escuchado]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'El metrónomo y la mielina', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: practicar lento no es perder el tiempo: es cómo el cerebro graba el movimiento]","explicacion":"[RELLENAR: la repetición precisa refuerza el camino neuronal; repetir con errores graba el error]","aplicacion":"[RELLENAR: baja el tempo hasta que salga perfecto y sube de 5 en 5]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 6, false, 'guion'),
    (v_mod, '3.7 Lectura rítmica en partitura', 'video', 'profunda', true, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: figuras, silencios, puntillo y síncopa]","practica":"[RELLENAR: leer el patrón del tumbado en partitura]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 7, false, 'guion'),
    (v_mod, 'El groove es primero', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: tocar a tiempo es tocar bonito]","historia_personal":"[RELLENAR: un músico que admiras por su groove más que por su técnica]","pregunta_al_alumno":"[RELLENAR: ¿tu público baila o sólo escucha?]"}'::jsonb, 8, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M4 · El mapa: notas, intervalos y grados', 4, 'principal', 'Entender lo que tocas para no volver a depender de un tutorial.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '4.1 Las notas en el diapasón', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: notas naturales, sostenidos/bemoles y los atajos de octava]","practica":"[RELLENAR: encontrar la misma nota en 3 lugares; juego de velocidad]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: nombrar todas las notas de la 6a y 5a cuerda en menos de 1 minuto]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '4.2 Intervalos que suenan a corrido', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: 3ras y 6tas: el sonido de las segundas voces y del requinto]","practica":"[RELLENAR: tocar 3ras y 6tas sobre una escala mayor]","criterio":"[RELLENAR: por qué el corrido ama las 3ras y 6tas paralelas]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '4.3 Grados: por qué los corridos se “parecen”', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: I, IV, V, el V7 y el relativo menor]","practica":"[RELLENAR: la misma progresión en números tocada en 2 tonos]","criterio":"[RELLENAR: pensar en grados = poder tocar cualquier rola en cualquier tono]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '4.4 Progresiones típicas y transponer con capo', 'video', 'herramienta', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: las progresiones más comunes del tumbado en grados]","practica":"[RELLENAR: subir la progresión con capo para la voz de un cantante]","criterio":"[RELLENAR: cuándo transportar con capo y cuándo cambiar de posición]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '4.5 Rola ancla 2 en 3 tonos', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: tocar la rola ancla 2 en su tono original y en 2 tonos más]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: la teoría mínima para tocar esto: 1 a 3 ideas + una analogía tuya]","practica":"[RELLENAR: de acordes a grados y de grados al tono nuevo]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: grabarla en el tono de su voz (o de un cantante que conozca)]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '¿Por qué La = 440?', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: la nota La que usa tu afinador vibra 440 veces por segundo]","explicacion":"[RELLENAR: de dónde sale ese estándar y por qué no siempre fue así]","aplicacion":"[RELLENAR: por qué tu docerola afinada a 440 empata con cualquier pista]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 5, false, 'guion'),
    (v_mod, '4.6 Partitura desde cero', 'video', 'profunda', true, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: pentagrama, clave de sol, figuras y dónde está cada nota en el diapasón]","practica":"[RELLENAR: leer una melodía sencilla del género en partitura]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 6, false, 'guion'),
    (v_mod, '4.7 Intervalos completos y armonía funcional', 'video', 'profunda', true, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: todos los intervalos, tónica/subdominante/dominante]","practica":"[RELLENAR: analizar una rola completa por funciones]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 7, false, 'guion'),
    (v_mod, 'Quiz del mapa', 'quiz', 'evaluacion', true, false, 'ninguno',
     '{"instrucciones":"[RELLENAR: comprueba que ya entiendes el mapa antes de meterte a las escalas]","preguntas":[{"pregunta":"En tono de G, ¿cuáles son los grados I, IV y V?","opciones":["G, C, D","G, A, B","G, D, E"],"correcta":0,"explicacion":"G (I), C (IV), D (V)."},{"pregunta":"¿Cuál es el relativo menor de C?","opciones":["Em","Am","Dm"],"correcta":1,"explicacion":"Comparten las mismas notas: Am es el VI de C."},{"pregunta":"¿Qué intervalo hay de C a E?","opciones":["Tercera mayor","Quinta justa","Segunda mayor"],"correcta":0},{"pregunta":"¿En qué traste está la octava de una cuerda al aire?","opciones":["7","12","5"],"correcta":1},{"pregunta":"Si pones el capo en el traste 2 y tocas la forma de G, ¿qué acorde suena?","opciones":["G","A","F"],"correcta":1,"explicacion":"Cada traste sube medio tono: G + 2 semitonos = A."}]}'::jsonb, 8, false, 'guion'),
    (v_mod, 'Entender vs memorizar', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: el que memoriza depende del tutorial; el que entiende saca cualquier rola]","historia_personal":"[RELLENAR: la primera vez que entendiste algo que antes sólo repetías]","pregunta_al_alumno":"[RELLENAR: ¿qué rola te sabes “de memoria” pero no entiendes?]"}'::jsonb, 9, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M5 · Escalas como recurso', 5, 'principal', 'Digitación y escalas para frasear, no para hacer ejercicios. Termina con tu primer requinto.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '5.1 Pentatónica: frases, no cajas', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: la pentatónica menor y mayor; por qué no se piensa en 5 cajas sueltas]","practica":"[RELLENAR: frases típicas del género dentro de la pentatónica]","criterio":"[RELLENAR: en qué momentos de la rola suena bien y en cuáles se oye a rock]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '5.2 Mayor y menor natural', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: las dos escalas y su relación (relativos)]","practica":"[RELLENAR: recorridos en 2 posiciones útiles para el requinto]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '5.3 Menor armónica: el sabor tumbado', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: la 7a elevada y por qué hace que el V suene a dominante en tono menor]","practica":"[RELLENAR: frases con la menor armónica sobre i–V7]","criterio":"[RELLENAR: cuándo suena a tumbado y cuándo a otro género (flamenco, clásico)]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '5.4 Cromatismos y notas de paso', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: notas de paso cromáticas: “el caminado”]","practica":"[RELLENAR: conectar dos notas de la escala con un cromatismo a tiempo]","criterio":"[RELLENAR: la nota cromática va en tiempo débil; el error común es caer en ella]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '5.5 3ras y 6tas paralelas', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: armonizar una melodía en 3ras y 6tas dentro de la escala]","practica":"[RELLENAR: la misma frase sola, en 3ras y en 6tas]","criterio":"[RELLENAR: el sonido de “dos guitarras” del corrido clásico al tumbado]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '5.6 Rutinas de digitación con metrónomo', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: púa alterna vs economía; subir el tempo de 5 en 5]","practica":"[RELLENAR: rutina diaria de 10 minutos con metrónomo]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: registrar en la bitácora su tempo máximo limpio]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 5, false, 'guion'),
    (v_mod, '5.7 Tu primer requinto: intro de la rola ancla 3', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: tocar la intro de requinto de la rola ancla 3 a tempo]","gancho":"[RELLENAR: toca la intro completa a tempo con la pista]","minimo":"[RELLENAR: de qué escala salen las notas y qué técnica pide]","practica":"[RELLENAR: frase por frase con la tablatura interactiva: 50% → 75% → 100%]","criterio":"[RELLENAR: qué la hace sonar a tumbado: ataque, apagados, dinámica]","reto":"[RELLENAR: grabarse tocando la intro sobre la pista]","puente":"[RELLENAR: estás a la mitad: toca demostrar lo aprendido (y tu primera revisión va por nuestra cuenta)]"}'::jsonb, 6, false, 'guion'),
    (v_mod, 'Por qué la pentatónica “no falla”', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: la pentatónica no tiene semitonos: casi no hay notas que choquen]","explicacion":"[RELLENAR: sin semitonos no hay tensión fuerte entre notas vecinas]","aplicacion":"[RELLENAR: empieza a improvisar con ella; las notas “sabrosas” vienen después]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 7, false, 'guion'),
    (v_mod, '5.8 Modos y menor melódica', 'video', 'profunda', true, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: los modos más útiles para el género y la menor melódica]","practica":"[RELLENAR: una frase en cada modo sobre el mismo acorde]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 8, false, 'guion'),
    (v_mod, 'La escala es un mapa, no el viaje', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: saber escalas no es saber frasear]","historia_personal":"[RELLENAR: un músico que toca pocas notas y dice mucho]","pregunta_al_alumno":"[RELLENAR: ¿qué quieres decir con tu requinto?]"}'::jsonb, 9, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'Hito de mitad: Evaluación 1-A', 6, 'evaluacion', 'Demuestra lo aprendido con una canción intermedia. Tu primera revisión personal va incluida.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, 'Evaluación 1-A: tablatura interactiva', 'tab', 'evaluacion', true, false, 'ninguno',
     '{"instrucciones":"[RELLENAR: cómo estudiar la canción intermedia con la tablatura: tempo, repetición de compases, pistas]"}'::jsonb, 0, false, 'guion'),
    (v_mod, 'Evaluación 1-A: canción intermedia', 'entrega', 'evaluacion', true, false, 'revision',
     '{"instrucciones":"[RELLENAR: qué canción es, qué partes tocar y a qué tempo; primero autoevalúate con la rúbrica]","entregables":"[RELLENAR: video tocando la canción sobre la pista sin guitarra (se ven las dos manos)]","rubrica":[{"criterio":"Tempo y pulso","niveles":["[RELLENAR: se acelera o se frena]","[RELLENAR: aguanta el tempo con tropiezos]","[RELLENAR: estable a tempo meta]","[RELLENAR: pulso de disco, con groove]"]},{"criterio":"Limpieza","niveles":["[RELLENAR: cuerdas que zumban o no suenan]","[RELLENAR: limpio en lo lento]","[RELLENAR: limpio a tempo]","[RELLENAR: limpio y con control del apagado]"]},{"criterio":"Fidelidad de la frase","niveles":["[RELLENAR: se pierde la melodía]","[RELLENAR: se reconoce la frase]","[RELLENAR: frase completa y correcta]","[RELLENAR: frase con los adornos del original]"]},{"criterio":"Sonido y dinámica","niveles":["[RELLENAR: todo al mismo volumen]","[RELLENAR: algo de contraste]","[RELLENAR: dinámica intencional]","[RELLENAR: suena a grabación profesional]"]}],"cta_texto":"[RELLENAR: tu primera revisión personal va incluida: aprovéchala]"}'::jsonb, 1, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M6 · Oído de ladrón: escucha activa', 7, 'principal', 'Saca cualquier rola con tu oído, el 0.5x y la IA. Roba ideas con criterio.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '6.1 Las capas de una rola', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: quién hace qué: requinto, docerola, tololoche, voz, percusión]","practica":"[RELLENAR: escuchar la misma rola 4 veces, cada vez siguiendo un instrumento]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: describir qué hace la docerola en el coro de una rola que le guste]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '6.2 Aísla el requinto o la docerola con IA', 'video', 'herramienta', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: qué hacen Moises y LALAL.ai y qué no pueden hacer]","practica":"[RELLENAR: flujo paso a paso: subir la rola, separar, bajar la pista de guitarra]","criterio":"[RELLENAR: calidad de la separación y cuándo confiar en ella]","reto":"[RELLENAR: aislar la guitarra de una rola que quiera sacar]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '6.3 Saca frases a oído en 0.5x', 'video', 'herramienta', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: ralentizar sin cambiar el tono; frases cortas, una nota a la vez]","practica":"[RELLENAR: sacar una frase de 2 compases en vivo, pensando en voz alta]","criterio":"[RELLENAR: cuándo usar 0.5x y cuándo 0.75x]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '6.4 Tono y capo de cualquier rola en 2 minutos', 'video', 'herramienta', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: encontrar la tónica con el bajo y la última nota; deducir el capo]","practica":"[RELLENAR: 3 rolas distintas, cronometrado]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '6.5 Transcribe tu primera frase', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: escribir en tab: TuxGuitar (gratis), Guitar Pro o papel]","practica":"[RELLENAR: transcribir la frase de 6.3 y comprobarla con la tablatura interactiva]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: transcribir 1 frase nueva y subirla a su banco de licks]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '6.6 Tu banco de licks', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: cómo archivar lo que robas: rola, compás, tono, técnica]","practica":"[RELLENAR: llenar la plantilla del banco de licks con 3 frases]","criterio":"[RELLENAR: un lick sin contexto no sirve: anota en qué acorde vive]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'Cómo separa pistas una IA', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: la IA “aprendió” cómo suena una guitarra escuchando miles de canciones]","explicacion":"[RELLENAR: redes neuronales entrenadas con pistas separadas; por qué a veces deja residuos]","aplicacion":"[RELLENAR: si la separación suena rara, compara con la mezcla original]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 6, false, 'guion'),
    (v_mod, 'Ralentizar sin cambiar el tono', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: tu reproductor puede ir a la mitad sin que suene grave]","explicacion":"[RELLENAR: time-stretching: estirar el tiempo sin tocar la frecuencia]","aplicacion":"[RELLENAR: usa 0.5x para aprender y 1x para comprobar]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 7, false, 'guion'),
    (v_mod, 'Roba como artista', 'video', 'filosofia', false, false, 'mentoria',
     '{"idea":"[RELLENAR: copiar → entender → transformar; la diferencia entre inspirarse y plagiar]","historia_personal":"[RELLENAR: una idea que robaste y convertiste en tuya]","pregunta_al_alumno":"[RELLENAR: ¿de quién vas a robar esta semana y qué vas a transformar?]","cta_texto":"[RELLENAR: la rola que no te sale: tráela a la sesión en vivo]"}'::jsonb, 8, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M7 · Armonía con criterio', 8, 'principal', 'Voicings, bajos, dominantes secundarias y rearmonizar sin arruinar la rola.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '7.1 Voicings de docerola', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: el mismo acorde en 3 posiciones: registro y octavas en la 12]","practica":"[RELLENAR: qué voicing usar en estrofa vs coro]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '7.2 Inversiones y bajos: el diálogo con el tololoche', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: inversiones y bajos de paso]","practica":"[RELLENAR: caminar el bajo entre acordes sin pisar al tololoche]","criterio":"[RELLENAR: cuándo la docerola deja el bajo libre]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '7.3 Dominantes secundarias y acordes de paso', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: el V del V y los acordes de paso típicos del género]","practica":"[RELLENAR: meter una dominante secundaria en una progresión conocida]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '7.4 Armonizar una melodía', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: de la nota de la melodía al acorde que la sostiene]","practica":"[RELLENAR: armonizar la melodía de un coro conocido]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '7.5 Rearmonizar con gusto', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: sustituir sin cambiar la función]","practica":"[RELLENAR: 3 rearmonizaciones de la misma progresión]","criterio":"[RELLENAR: cuándo la rearmonización suma y cuándo le estorba a la voz]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '7.6 Rola ancla 4 con arreglo armónico propio', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: tocar la rola ancla 4 con al menos 2 decisiones armónicas propias]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: la teoría mínima para tocar esto: 1 a 3 ideas + una analogía tuya]","practica":"[RELLENAR: pasos, digitación y tempo: lento → 0.5x → tempo real]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: grabarla y explicar en la bitácora qué cambió y por qué]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'Por qué el acorde mayor “suena feliz”', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: el acorde mayor ya vive escondido dentro de una sola nota]","explicacion":"[RELLENAR: la serie de armónicos: una cuerda vibra en varias frecuencias a la vez]","aplicacion":"[RELLENAR: por eso los acordes mayores al aire suenan tan llenos en la 12]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 6, false, 'guion'),
    (v_mod, '7.7 Sustituciones', 'video', 'profunda', true, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: sustitución tritonal, intercambio modal]","practica":"[RELLENAR: aplicarlas a una rola del género con medida]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 7, false, 'guion'),
    (v_mod, 'Toca para la rola, no para lucirte', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: menos es más: el acompañante sirve a la canción]","historia_personal":"[RELLENAR: una vez que te pasaste de notas (o viste a alguien hacerlo)]","pregunta_al_alumno":"[RELLENAR: ¿qué le quitarías a tu arreglo para que la voz brille más?]"}'::jsonb, 8, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M8 · Técnicas de los grandes', 9, 'principal', 'Ligados, bends, trémolo, armónicos, pinch harmonic y sweep: recursos, no trucos.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '8.1 Ligados y arrastres', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: hammer-on, pull-off y slide]","practica":"[RELLENAR: frases típicas del requinto con ligados]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '8.2 Bends y vibrato', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: cuánto subir y cómo afinar el bend]","practica":"[RELLENAR: bends a 1/2 y 1 tono comparando con la nota real]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '8.3 Trémolo y picado rápido', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: trémolo con la muñeca relajada]","practica":"[RELLENAR: subir el tempo del picado de 5 en 5]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '8.4 Armónicos naturales, artificiales y pinch harmonic', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: dónde están los armónicos y cómo sacar el pinch con la púa y el pulgar]","practica":"[RELLENAR: armónicos en 12, 7 y 5; pinch en una frase]","criterio":"[RELLENAR: cuándo un armónico adorna y cuándo distrae]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '8.5 Sweep picking aplicado al corrido', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: barrido de 3 cuerdas y cómo apagar las que no suenan]","practica":"[RELLENAR: arpegio barrido sobre un acorde del género]","criterio":"[RELLENAR: el sweep en el tumbado: dónde lo has escuchado y cuánto usarlo]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '8.6 Robar técnicas de otros géneros', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: rock, jazz, flamenco: qué se adapta bien al corrido]","practica":"[RELLENAR: una frase de otro género llevada al tumbado]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'Nodos: por qué los trastes 12, 7 y 5', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: tocar el armónico del traste 12 divide la cuerda exactamente a la mitad]","explicacion":"[RELLENAR: nodos en 1/2, 1/3 y 1/4 de la cuerda = trastes 12, 7 y 5]","aplicacion":"[RELLENAR: busca armónicos donde la cuerda se divide en partes iguales]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 6, false, 'guion'),
    (v_mod, 'La física del pinch harmonic', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: el “chillido” sale de apagar la nota justo en un nodo]","explicacion":"[RELLENAR: el pulgar toca la cuerda al mismo tiempo que la púa y deja sonar sólo un armónico]","aplicacion":"[RELLENAR: mueve el punto de ataque para encontrar distintos armónicos]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 7, false, 'guion'),
    (v_mod, 'Evaluación 1-B: tablatura interactiva', 'tab', 'evaluacion', true, false, 'ninguno',
     '{"instrucciones":"[RELLENAR: cómo estudiar la canción avanzada con la tablatura]"}'::jsonb, 8, false, 'guion'),
    (v_mod, 'Evaluación 1-B: canción avanzada', 'entrega', 'evaluacion', true, false, 'ninguno',
     '{"instrucciones":"[RELLENAR: qué canción es, qué partes tocar y a qué tempo; primero autoevalúate con la rúbrica]","entregables":"[RELLENAR: video tocando la canción sobre la pista sin guitarra]","rubrica":[{"criterio":"Tempo y pulso","niveles":["[RELLENAR: se acelera o se frena]","[RELLENAR: aguanta el tempo con tropiezos]","[RELLENAR: estable a tempo meta]","[RELLENAR: pulso de disco, con groove]"]},{"criterio":"Limpieza","niveles":["[RELLENAR: cuerdas que zumban o no suenan]","[RELLENAR: limpio en lo lento]","[RELLENAR: limpio a tempo]","[RELLENAR: limpio y con control del apagado]"]},{"criterio":"Fidelidad de la frase","niveles":["[RELLENAR: se pierde la melodía]","[RELLENAR: se reconoce la frase]","[RELLENAR: frase completa y correcta]","[RELLENAR: frase con los adornos del original]"]},{"criterio":"Sonido y dinámica","niveles":["[RELLENAR: todo al mismo volumen]","[RELLENAR: algo de contraste]","[RELLENAR: dinámica intencional]","[RELLENAR: suena a grabación profesional]"]}]}'::jsonb, 9, false, 'guion'),
    (v_mod, 'El truco no es la canción', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: la técnica al servicio de la música]","historia_personal":"[RELLENAR: un solo que te impresionó por lo que dijo, no por lo rápido]","pregunta_al_alumno":"[RELLENAR: ¿qué técnica estás usando para esconderte?]"}'::jsonb, 10, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M9 · Adornos e improvisación con criterio', 10, 'principal', 'Rellenos, pregunta y respuesta con la voz, notas objetivo y tu requinto de intro.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '9.1 El vocabulario del relleno', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: los rellenos típicos entre frases de la voz]","practica":"[RELLENAR: 5 rellenos para el mismo hueco]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '9.2 Pregunta y respuesta con la voz', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: dejar espacio: el requinto contesta, no interrumpe]","practica":"[RELLENAR: rellenar sólo en los huecos de una pista con voz]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '9.3 Notas objetivo sobre una progresión', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: caer en notas del acorde en el tiempo fuerte]","practica":"[RELLENAR: improvisar apuntando a la 3a de cada acorde]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '9.4 Un requinto de intro con motivos', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: motivo, repetición y variación]","practica":"[RELLENAR: construir una intro de 8 compases a partir de un motivo de 3 notas]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '9.5 Tres versiones del mismo relleno', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: decidir es parte de tocar]","practica":"[RELLENAR: grabar 3 versiones y elegir una]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: explicar en la bitácora por qué eligió esa versión]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, 'Tu cerebro en flow', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: al improvisar bien, una parte del cerebro que te juzga baja su actividad]","explicacion":"[RELLENAR: qué pasa en el cerebro de un músico improvisando (estudios con resonancia)]","aplicacion":"[RELLENAR: practica tanto que puedas dejar de pensar al tocar]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'El error como información', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: el error no es fracaso, es el dato que te dice qué practicar]","historia_personal":"[RELLENAR: un error en vivo que te enseñó algo]","pregunta_al_alumno":"[RELLENAR: ¿qué error repites y qué te está diciendo?]"}'::jsonb, 6, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'M10 · Crea: melodías y rasgueo para temas inéditos', 11, 'principal', 'De la letra al arreglo: rasgueo, progresión, requinto propio y maqueta.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, '10.1 De la letra al rasgueo', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: elegir el rasgueo por la métrica y el tempo de la letra]","practica":"[RELLENAR: 3 letras distintas, 3 rasgueos distintos]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 0, false, 'guion'),
    (v_mod, '10.2 La progresión de un tema nuevo', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: crear la progresión desde la melodía o desde el feeling]","practica":"[RELLENAR: armar la progresión de un tema propio]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, '10.3 Componer el requinto: intro, rellenos y puente', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: el requinto como segunda voz de la canción]","practica":"[RELLENAR: escribir la intro y 2 rellenos de un tema propio]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 2, false, 'guion'),
    (v_mod, '10.4 IA como coautor, no como autor', 'video', 'herramienta', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: qué sí le pides a la IA (ideas, pistas de práctica, maquetas) y qué no]","practica":"[RELLENAR: flujo real: de una idea tuya a una maqueta con apoyo de IA]","criterio":"[RELLENAR: límites éticos y derechos sobre lo que genera una IA]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 3, false, 'guion'),
    (v_mod, '10.5 Maqueta en casa', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: celular vs interfaz: lo mínimo para que se escuche decente]","practica":"[RELLENAR: grabar docerola + requinto en capas]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 4, false, 'guion'),
    (v_mod, '10.6 Tu siguiente nivel: grabar en estudio', 'video', 'nucleo', false, false, 'estudio',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: qué cambia de una maqueta a una producción]","practica":"[RELLENAR: recorrido por una sesión real en el estudio]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]","cta_texto":"[RELLENAR: graba tu arreglo en ARIDO con precio de alumno]"}'::jsonb, 5, false, 'guion'),
    (v_mod, 'Registra tu obra en 60 segundos', 'video', 'capsula', true, false, 'ninguno',
     '{"dato":"[RELLENAR: tu canción es tuya desde que la creas, pero registrarla te protege]","explicacion":"[RELLENAR: qué es el registro de obra (INDAUTOR en México) y para qué sirve; aclarar que no es asesoría legal]","aplicacion":"[RELLENAR: registra tus temas antes de subirlos]","fuente":"[RELLENAR: dónde se verifica el dato (libro, fabricante, artículo) — no se le muestra al alumno]"}'::jsonb, 6, false, 'guion'),
    (v_mod, 'El músico completo', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: oficio, negocio y disciplina: tocar bien es sólo una parte]","historia_personal":"[RELLENAR: lo que aprendiste del negocio de la música que nadie te enseñó]","pregunta_al_alumno":"[RELLENAR: ¿qué músico quieres ser en 5 años?]"}'::jsonb, 7, false, 'guion');

  insert into public.curso_modulos (curso_id, titulo, orden, ruta, descripcion)
    values (v_curso, 'Graduación', 12, 'principal', 'Tu arreglo de requinto, tu plan de 90 días y tu certificado.') returning id into v_mod;
  insert into public.curso_lecciones
    (modulo_id, titulo, tipo, etiqueta, opcional, preview, cta, contenido, orden, publicada, estado_produccion) values
    (v_mod, 'Evaluación 2: tu arreglo de requinto', 'entrega', 'evaluacion', true, false, 'ninguno',
     '{"instrucciones":"[RELLENAR: elegir la rola, crear el arreglo de requinto (intro, rellenos, final) y autoevaluarse]","entregables":"[RELLENAR: video tocándolo + tablatura (TuxGuitar/Guitar Pro/foto) + texto: “por qué elegí esto”]","rubrica":[{"criterio":"Coherencia armónica","niveles":["[RELLENAR: notas que chocan]","[RELLENAR: funciona con choques ocasionales]","[RELLENAR: todo encaja con la armonía]","[RELLENAR: usa tensiones a propósito]"]},{"criterio":"Fraseo y estilo tumbado","niveles":["[RELLENAR: no suena a corrido]","[RELLENAR: se reconoce el género]","[RELLENAR: suena a corrido tumbado actual]","[RELLENAR: tiene sello propio dentro del estilo]"]},{"criterio":"Técnica","niveles":["[RELLENAR: errores que distraen]","[RELLENAR: ejecución aceptable]","[RELLENAR: ejecución limpia]","[RELLENAR: técnica al servicio de la rola]"]},{"criterio":"Identidad","niveles":["[RELLENAR: copia literal]","[RELLENAR: variación de algo conocido]","[RELLENAR: ideas propias]","[RELLENAR: se reconoce quién lo tocó]"]},{"criterio":"Criterio explicado","niveles":["[RELLENAR: no explica sus decisiones]","[RELLENAR: explica qué hizo]","[RELLENAR: explica por qué]","[RELLENAR: explica alternativas que descartó y por qué]"]}]}'::jsonb, 0, false, 'guion'),
    (v_mod, 'G.1 Tu plan de 90 días', 'video', 'nucleo', false, false, 'ninguno',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: cómo mantener y seguir subiendo el nivel sin el curso]","practica":"[RELLENAR: armar la rutina semanal con la plantilla de 90 días]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]"}'::jsonb, 1, false, 'guion'),
    (v_mod, 'G.2 Tu certificado y lo que sigue', 'video', 'nucleo', false, false, 'mentoria',
     '{"objetivo":"[RELLENAR: “Al terminar podrás…”: qué toca el alumno al final y a qué tempo]","gancho":"[RELLENAR: el pasaje que tocas en los primeros 30 s para enseñar a dónde va a llegar]","minimo":"[RELLENAR: los 2 certificados: de término y con mención]","practica":"[RELLENAR: cómo descargarlo y compartirlo]","criterio":"[RELLENAR: cuándo sí, cuándo no y por qué suena a corrido; rola de ejemplo y error común]","reto":"[RELLENAR: tarea medible: tempo meta, repeticiones limpias o grabarse]","puente":"[RELLENAR: adelanto de la siguiente lección en una frase]","cta_texto":"[RELLENAR: mentoría grupal semanal con precio fundador para graduados]"}'::jsonb, 2, false, 'guion'),
    (v_mod, 'Carta final', 'video', 'filosofia', false, false, 'ninguno',
     '{"idea":"[RELLENAR: el mensaje que quieres que se lleven para toda la vida]","historia_personal":"[RELLENAR: por qué hiciste este curso]","pregunta_al_alumno":"[RELLENAR: ¿qué vas a tocar mañana?]"}'::jsonb, 3, false, 'guion');

end $$;
